name: Update README

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 */1 * * *"

jobs:
  markscribe:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master

      - name: Download markscribe
        run: curl -fsSL https://github.com/muesli/markscribe/releases/download/v0.6.0/markscribe_0.6.0_linux_x86_64.tar.gz | tar -xzf - markscribe
      - env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_GITHUB_TOKEN }}
        run: ./markscribe -write README.md templates/README.md.tpl

      - uses: EndBug/add-and-commit@a94899bca583c204427a224a7af87c02f9b325d5 # v9
        with:
          message: "chore(ci): Update generated README"
          default_author: github_actions
          push: true
          add: README.md
